ARG FROM_IMAGE

FROM ${FROM_IMAGE}

ARG USERID
ARG USERNAME
ARG INSTALL_SCRIPT

RUN adduser -D -u ${USERID} ${USERNAME}

COPY ./${INSTALL_SCRIPT} /install.sh
RUN chmod +x /install.sh
RUN /install.sh
RUN rm -f /install.sh

USER ${USERNAME}
WORKDIR /project

# use cached .m2, .ivy2, .blaze for faster builds
RUN ln -s /project/.buildx-cache/blaze ~/.blaze
RUN ln -s /project/.buildx-cache/m2 ~/.m2
RUN ln -s /project/.buildx-cache/ivy2 ~/.ivy2
