ARG FROM_IMAGE

FROM ${FROM_IMAGE}

ARG USERID
ARG USERNAME
ARG INSTALL_SCRIPT

RUN groupadd -g ${USERID} ${USERNAME}
RUN useradd -m -l -u ${USERID} -g ${USERNAME} ${USERNAME}

COPY ./${INSTALL_SCRIPT} /install.sh
RUN chmod +x /install.sh
RUN /install.sh
RUN rm -f /install.sh

USER ${USERNAME}
WORKDIR /project

# use cached .m2 and .ivy2 for faster builds
RUN ln -s /project/.buildx-cache/m2 ~/.m2
RUN ln -s /project/.buildx-cache/ivy2 ~/.ivy2
